name    'reidmv-augeasprovider'
version '0.0.2'
source 'git://github.com/reidmv/puppet-module-augeasprovider/tree/core_only'
author 'Dominic Cleal, Raphael Pinson'
license 'Apache 2.0'
summary 'Alternative Augeas-based providers for Puppet'
description 'This module provides alternative providers for core Puppet types using the Augeas configuration API library.'
project_page 'http://github.com/reidmv/puppet-module-augeasprovider/tree/core_only'
